# BUS 32120, Week 3
## Fixing errors in numeric data using `Pandas`

When you import data into Pandas, it will try to read the first 1000 rows to determine the datatype for each column. Recall that every column in a Pandas DataFrame can have only one datatype. This means that even if the first 999 rows are numeric, if the 1000th row is a string, the whole column will import as a string. 

You'll often be dealing with datasets where many rows are numeric, but several rows have either incorrectly coded data or errors. You'll have to remove those rows or otherwise deal with them. 

Even more frequently, you'll have to deal with datasets where there's a column of numeric data that includes a special character, such as a dollar sign or a comma. You may expect Pandas to know that these are numbers, but Pandas won't know this! It will import these columns as strings. You'll have to somehow remove the offending special character then convert (the jargon word is "cast") the column to a numeric type. 

Below you'll find 3 examples:
* Cast numeric data with a dollar sign
* Cast numeric data with a comma
* Force a column that includes errors (e.g. strings) to be cast to numeric

In [1]:
import pandas as pd

In [2]:
# Create a sample DataFrame with various numeric columns needing cleanup
data = {
    'Price': ['$100.00', '$200.50', '$300.75', '$400.00'],
    'Revenue': ['1,000', '2,500', '3,750', '5,000'],
    'Quantity': ['10', '15', '20', 'twenty-five'],  
}

In [3]:
df = pd.DataFrame(data)

In [4]:
# Visually examine the first few rows of the imported data
df.head()

     Price Revenue     Quantity
0  $100.00   1,000           10
1  $200.50   2,500           15
2  $300.75   3,750           20
3  $400.00   5,000  twenty-five

In [5]:
# Examine data types of each column 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Price     4 non-null      object
 1   Revenue   4 non-null      object
 2   Quantity  4 non-null      object
dtypes: object(3)
memory usage: 228.0+ bytes

In [6]:
# let's revisit the original dataframe to remind ourselves what the issues are
print("Original DataFrame:")
df # DON'T PUT THE DF ITSELF INSIDE A PRINT! If you do print(df), you'll get rid of all the helpful formatting

Original DataFrame:

     Price Revenue     Quantity
0  $100.00   1,000           10
1  $200.50   2,500           15
2  $300.75   3,750           20
3  $400.00   5,000  twenty-five

### 1. Remove the dollar sign from the 'Price' column and convert to numeric

**regex** in the parameters stands for regular expressions. In short, regular expressions are a way of programatically searching for a pattern in a string, e.g. all strings that start with a capital letter. Regular expressions are generally hard to write and are beyond the scope of what we'll use in this class. 

All you need to know here is that we're looking for the special character '$' and replacing it with '' (aka an emptry string, basically removing it). 

In the following, we have to use  because '$' is a special character. The \ is called an "escape character." The details of this don't matter too much, just know that sometimes you'll need to put a slash in front of some special characters. The easiest way to know if you need to is to try it without the slash, then add the slash if you get an error.

In [8]:
df['Price'] = df['Price'].replace({'\$': ''}, regex=True).astype(float)

### 2. Remove commas from the 'Revenue' column and convert to numeric

No '\' is needed here because , is not a special character.

In [8]:
df['Revenue'] = df['Revenue'].replace({',': ''}, regex=True).astype(float)

### 3. Convert the 'Quantity' column to numeric

For this type of error, we can't automatically fix strings like "twenty five" and turn them into numbers in Pandas (at least, not yet!). What we'll do instead is **coerce** Pandas to convert/cast the data to numeric. When Pandas runs into rows where it can't turn the value into a number, it will turn it into a NULL instead.

In [9]:
# setting errors='coerce' to handle strings like 'twenty-five'
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [10]:
# Notice how in row 4 the quantity is "NaN", meaning "not a number" aka NULL 
print("\nCleaned DataFrame:")
df

Cleaned DataFrame:

    Price  Revenue  Quantity
0  100.00   1000.0      10.0
1  200.50   2500.0      15.0
2  300.75   3750.0      20.0
3  400.00   5000.0       NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Price     4 non-null      float64
 1   Revenue   4 non-null      float64
 2   Quantity  3 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes